name: CI

on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: checkout@v2
        with:
          fetch-depth: 2

      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: '3.10'
      - name: Generate Report
        run: |
          poetry install --no-root --no-interaction
          pytest --cov=app tests/
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
